from promptArgs.promptArgsClass import PromptArgs 

naming_conventions = """
- "Travel: [Destination]" → If it's about a featured travel location.
- "Feature [#]: [Topic]" → If it is a highlighted research or cultural feature.
- "News [#]: [Topic]" → If it belongs to a general news section.
- "Header: Alumni Lockup" → If it is a branding-related link near the top.
- "Events [#]: [Event Name]" → If it is part of an events section.
- "Footer: The Current" → If it links to UCSB’s news portal in the footer.
- "Footer: Subscribe to the Magazine" → If it links to UCSB's digital magazine in the footer.
- "Advertisement: [Sponsor Name]" → If it is a promotional or external link.
"""

link_names_example_one = """
- Alumni Tours: Galapagos. Start Exploring!
- Explore the study
- Tour the exhibit
- check out the results
- meet the tiny tenants
- tune into something new
- Meet Marzieh
- UC Santa Barbara Alumni
- View all events
- The Current
- Register link: UC Alumni Career Network
- GoGoleta
- register for the webinar
- Make your voice heard
- Subscribe to the Magazine
"""

generated_link_names_example_one = """
- Travel: Apulia
- Feature 1: Maternal Brain
- Feature 3: Immersive Ocean Health
- News 2: Semiconductor work
- News 3: Electrons
- News 1: Plastic Recycling
- Feature 2: Mahsa Imini
- Header: Alumni Lockup
- Events 2: UCSB Soccer + Fanfest
- Footer: The Current
- Events 1: International Employment
- Advertisement: GoGoleta
- Events 2: UCSB Soccer + Fanfest
- Feature 4: Register to Vote
- Footer: Subscribe to the Magazine
"""

html_example_one = """
<body class="e2ma-design-option-backdrop e2ma-template" data-e2ma-styles="background" style="-webkit-font-smoothing: antialiased;background-repeat: repeat;padding: 0;width: 100% !important;background-attachment: scroll;-moz-osx-font-smoothing: grayscale;background-position: center center;margin: 0;background-color: #eef0f2">
<div style="display: none !important; mso-hide:all;">Plus travel to Italy, career opps &amp; more in your September @UCSB Newsletter</div>
<img alt="Plus travel to Italy, career opps &amp; more in your September @UCSB Newsletter" height="1" src="https://images.e2ma.net/images/spacer.gif" style="display: none !important; mso-hide:all;" width="1"/>
<div class="e2ma-design-option-backdrop" data-e2ma-styles="background" style="-webkit-font-smoothing: antialiased;background-repeat: repeat;padding: 0;width: 100% !important;background-attachment: scroll;-moz-osx-font-smoothing: grayscale;background-position: center center;margin: 0;background-color: #eef0f2">
<table border="0" cellpadding="0" cellspacing="0" data-e2ma-color="#003660, #FEBC11, #047c91, #0BA89A, #DCE1E5, #DCD6CC," role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;-moz-osx-font-smoothing: grayscale; -webkit-font-smoothing: antialiased" width="100%">
<tbody><tr>
<td align="center" class="sanpad" style="padding:15px 0px">
<table align="center" border="0" cellpadding="0" cellspacing="0" class="mobile-width-nopad" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;width: 640px">
<tbody>
<tr>
<td valign="top">
<table border="0" cellpadding="0" cellspacing="0" class="mobile-width-nopad" id="template_container" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;width: 640px">
<tbody>
<tr>
<td style="padding-bottom:10px" valign="top">
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-row-region-content e2ma-section" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"><tbody><tr><td class="e2ma-layout-column-content"></td></tr></tbody></table> <div class="e2ma-single-column-layout e2ma-section"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"><tbody><tr><td class="e2ma-design-option-template" data-e2ma-styles="background, border-left, border-right" style="background-color: #fff">
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_whotrluq" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 2px 40px 3px 40px;background-color: #047c91" valign="top"> <div class="e2ma-content-block"> <h4 style="display: block;font-size: 15px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660"><span class="e2ma-style" style="color: rgb(255, 255, 255); font-size: 10px; text-decoration: underline"><b><a data-name="View in browser" data-type="url" href="#" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;color: rgb(255, 255, 255)">View in your browser</a></b></span></h4> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_xsnehhzu" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://www.alumni.ucsb.edu/?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="UC Santa Barbara Alumni" border="0" height="87" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/50/bd/de/b0/0e260a18107bc5ed6dfd264d_1280x174.png" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_wzbnutxr" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 10px"><span style="line-height: 1.5"><strong><span class="e2ma-style" style="font-size: 28px"><span class="e2ma-style" style="color: rgb(0, 54, 96)">@UCSB </span></span></strong><span class="e2ma-style" style="font-size: 16px"><span class="e2ma-style" style="color: rgb(0, 54, 96)">Graduate Edition September 2024</span></span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_rokktpnu" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 0 0 0;background-color: transparent" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://news.ucsb.edu/2024/021611/new-study-reveals-changes-brain-throughout-pregnancy?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Maternal brain map" border="0" height="320" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/43/e7/c1/95/1e41656e10b64daed3c3eff8_1280x640.jpg" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_sqhgqikj" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 30px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h1 style="display: block;font-size: 30px;font-weight: bold;margin: 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;line-height: 36.4px">Revealing maternal brain map<br/></h1>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_pfbneqqk" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 20px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5">Researchers in Emily Jacobs’ lab at UC Santa Barbara reveal the first-ever map of a human brain over the course of pregnancy.</span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer e2ma-button" id="block_knfdwwqk" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="e2ma-holder" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;padding: 0 40px 60px 40px;background-color: transparent" width="100%"> <tbody><tr> <td align="left"> <table class="c-collapsed-table" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;border-spacing: 0"> <tbody><tr> <td bgcolor="#047c91" style="-webkit-border-radius: 0px; -moz-border-radius: 0px; border-radius: 0px; box-sizing: border-box; "> <a href="https://news.ucsb.edu/2024/021611/new-study-reveals-changes-brain-throughout-pregnancy?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline; padding: 12px 18px; font-size: 16px; font-family: 'Century Gothic', 'Apple Gothic', 'URW Gothic L', Futura, Arial, sans-serif; color: #ffffff; text-align: center; text-decoration: none; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; background-color: #047c91; font-style: normal; font-weight: bold; display: block; border: 1px solid #047c91; mso-line-height-rule: exactly; line-height:110%">Explore the study</a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_tpgpxbjx" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 0 0 0;background-color: transparent" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://news.ucsb.edu/in-focus/first-mahsa-amini-fellow-begins-doctoral-program-religious-studies?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Meet Marzieh" border="0" height="320" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/ca/62/39/0a/ec0a748fe39996714c112724_1280x640.jpg" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_imtfddzk" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 30px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h1 style="display: block;font-size: 30px;font-weight: bold;margin: 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;line-height: 36.4px">Groundbreaking fellowship honoring Mahsa Amini selects first recipient<br/></h1>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_jmeavncq" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 20px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;text-indent: 0px"><span style="line-height: 1.5">Marzieh Gahvarband will pursue doctoral research delving into the complex dynamics behind recent social movements in Iran.</span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer e2ma-button" id="block_ppyokrtx" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="e2ma-holder" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;padding: 0 40px 60px 40px;background-color: transparent" width="100%"> <tbody><tr> <td align="left"> <table class="c-collapsed-table" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;border-spacing: 0"> <tbody><tr> <td bgcolor="#047c91" style="-webkit-border-radius: 0px; -moz-border-radius: 0px; border-radius: 0px; box-sizing: border-box; "> <a href="https://news.ucsb.edu/in-focus/first-mahsa-amini-fellow-begins-doctoral-program-religious-studies?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline; padding: 12px 18px; font-size: 16px; font-family: 'Century Gothic', 'Apple Gothic', 'URW Gothic L', Futura, Arial, sans-serif; color: #ffffff; text-align: center; text-decoration: none; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; background-color: #047c91; font-style: normal; font-weight: bold; display: block; border: 1px solid #047c91; mso-line-height-rule: exactly; line-height:110%">Meet Marzieh</a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_lbsbqzub" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0;background-color: transparent" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://news.ucsb.edu/2024/021608/immersive-ocean-health-project-premieres-ucsbs-allosphere-part-getty-pst-art?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="AlloSphere" border="0" height="320" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/93/b5/7f/99/c457f5f87cd82b62333ed893_1280x640.jpg" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_wnovwqwi" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h1 style="display: block;font-size: 30px;font-weight: bold;margin: 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;line-height: 36.4px">Immersive ocean health project premieres at UCSB's AlloSphere<br/></h1>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_wwmeilhf" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 20px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 25.2px"><span style="line-height: 1.5"><span class="e2ma-style" style="font-size: 16px; color: rgb(0, 54, 96)">The AlloSphere will host a series of public screenings as part of Getty PST ART: Art and Science Collide.</span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer e2ma-button" id="block_vizagykj" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="e2ma-holder" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;padding: 0 40px 60px 40px;background-color: transparent" width="100%"> <tbody><tr> <td align="left"> <table class="c-collapsed-table" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;border-spacing: 0"> <tbody><tr> <td bgcolor="#047c91" style="-webkit-border-radius: 0px; -moz-border-radius: 0px; border-radius: 0px; box-sizing: border-box; "> <a href="https://news.ucsb.edu/2024/021608/immersive-ocean-health-project-premieres-ucsbs-allosphere-part-getty-pst-art?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline; padding: 12px 18px; font-size: 16px; font-family: 'Century Gothic', 'Apple Gothic', 'URW Gothic L', Futura, Arial, sans-serif; color: #ffffff; text-align: center; text-decoration: none; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; background-color: #047c91; font-style: normal; font-weight: bold; display: block; border: 1px solid #047c91; mso-line-height-rule: exactly; line-height:110%">Tour the exhibit</a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_ohgnmcva" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0;background-color: transparent" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://www.universityofcalifornia.edu/get-involved/uc-votes?utm_source=ucsb-alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Register to vote: Oct 21" border="0" height="320" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/f1/c8/4d/f3/40a689939ba9f9aa41b9fca6_1280x640.jpg" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_eoppvjja" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h1 style="display: block;font-size: 30px;font-weight: bold;margin: 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;line-height: 36.4px">Get ready to vote on November 5<br/></h1>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_wexlowjb" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 20px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 25.2px"><span style="line-height: 1.5"><span class="e2ma-style" style="font-size: 16px; color: rgb(0, 54, 96)">We’re less than two months away from the 2024 election when your small efforts (registering and voting) can make a huge impact on local and national elections and policies.</span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer e2ma-button" id="block_xwvpclik" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="e2ma-holder" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;padding: 0 40px 60px 40px;background-color: transparent" width="100%"> <tbody><tr> <td align="left"> <table class="c-collapsed-table" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;border-spacing: 0"> <tbody><tr> <td bgcolor="#047c91" style="-webkit-border-radius: 0px; -moz-border-radius: 0px; border-radius: 0px; box-sizing: border-box; "> <a href="https://www.universityofcalifornia.edu/get-involved/uc-votes?utm_source=ucsb-alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline; padding: 12px 18px; font-size: 16px; font-family: 'Century Gothic', 'Apple Gothic', 'URW Gothic L', Futura, Arial, sans-serif; color: #ffffff; text-align: center; text-decoration: none; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; background-color: #047c91; font-style: normal; font-weight: bold; display: block; border: 1px solid #047c91; mso-line-height-rule: exactly; line-height:110%">Make your voice heard</a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_jaoydsil" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 30px 20px 40px;background-color: #003660" valign="top"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="1%"> <tbody><tr> <td style=" padding: 0px 20px 10px 0px; " valign="top" width="1%"> <div align="center" style="mso-table-lspace:0;mso-table-rspace:9"> <img alt="Trivia time!" border="0" height="44" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/95/5d/3b/b3/083ab9246f0f10b59b8fbcdd_88x88.png" style="display: block" width="44"/> </div>
</td> </tr> </tbody></table> <div class="e2ma-combo-content e2ma-content-block" style="font-size: 12px;line-height: 1.5">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h1 style="display: block;font-size: 30px;font-weight: bold;margin: 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 26px;line-height: 30px;font-weight: 600;color: #04859B;line-height: 36.4px"><span class="e2ma-style" style="color: rgb(254, 188, 17)">Gaucho Trivia</span><span class="e2ma-style" style="color: rgb(255, 255, 255)"></span></h1>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(255, 255, 255); font-size: 20px">WWhen did the UCSB vs. Cal-Poly aka Blue-Green Rivalry begin?</span></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(255, 255, 255)"><br/>Scroll to the bottom for the answer </span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_vatmmcnh" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 50px 40px 20px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <h4 style="display: block;font-size: 15px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660"><span class="e2ma-style" style="font-size: 30px"><strong>Join Us</strong></span><br/></h4> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_atsmcaih" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 35px 30px 40px;background-color: #fff" valign="top"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td valign="top" width="1%"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="1%"> <tbody><tr> <td style=" padding: 0px 20px 20px 0px; " valign="top" width="1%"> <div align="center" style="mso-table-lspace:0;mso-table-rspace:9"> <a href="https://ucop.zoom.us/webinar/register/WN_td2V_jyMQpCIXVABze-PQw#/registration" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="From local to global" border="0" height="217" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/78/04/c0/ef/5d3d0fb3583616d6911259be_434x434.jpg" style="display: block" width="217"/> </a> </div>
</td> </tr> </tbody></table> </td> <td valign="top"> <div class="e2ma-combo-content e2ma-content-block" style="font-size: 12px;line-height: 1.5"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 20.8px"><span style="line-height: 1.5"><span class="e2ma-style"><strong><strong><span class="e2ma-style" style="color: rgb(51, 51, 51); font-size: 15px"><span class="e2ma-style" style="font-size: 18px; color: rgb(4, 124, 145)">From local to global: key considerations for international employment</span><br/>Sept. 30, 2024 | 11am - 12pm | Virtual</span></strong></strong></span></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 20.8px"><span style="line-height: 1.5">Expand your job search. Learn how to succeed in the dynamic world of international employment.</span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 20.8px"><span style="line-height: 1.5"><a data-name="Register link: UC Alumni Career Network" data-type="url" href="https://ucop.zoom.us/webinar/register/WN_td2V_jyMQpCIXVABze-PQw#/registration" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline"><strong>Register for the webinar</strong></a><br/></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_voroysac" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 30px 40px;background-color: #fff" valign="top"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td valign="top" width="1%"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="1%"> <tbody><tr> <td style=" padding: 0px 20px 20px 0px; " valign="top" width="1%"> <div align="center" style="mso-table-lspace:0;mso-table-rspace:9"> <a href="https://www.campuscalendar.ucsb.edu/event/ucsb-vs-cal-poly-soccer-fanfest?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="UCSB Soccer - FanFest" border="0" height="217" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/53/70/54/67/30d550d907daa260febdbe9c_434x434.jpg" style="display: block" width="217"/> </a> </div>
</td> </tr> </tbody></table> </td> <td valign="top"> <div class="e2ma-combo-content e2ma-content-block" style="font-size: 12px;line-height: 1.5"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 20.8px"><span style="line-height: 1.5"><span class="e2ma-style" style="font-size: 18px; color: rgb(4, 124, 145)"><strong>UCSB Soccer + FanFest</strong></span><strong><span class="e2ma-style" style="color: rgb(4, 124, 145)"><br/></span><span class="e2ma-style" style="font-size: 15px; color: rgb(0, 0, 0)"><span class="e2ma-style" style="font-size: 16px; color: rgb(4, 124, 145)"><span class="e2ma-style" style="font-size: 18px"><strong><span class="e2ma-style" style="font-size: 15px; color: rgb(51, 51, 51)"> Oct. 6, 2024 | Harder Stadium <br/></span></strong></span></span></span></strong></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5">Bring your Gaucho pride to the Blue-Green Rivalry. Purchase your alumni discounted soccer tickets to cheer on the teams, then celebrate with Gauchos at FanFest.<br/></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"><strong><a data-name="register for the webinar" data-type="url" href="https://www.campuscalendar.ucsb.edu/event/ucsb-vs-cal-poly-soccer-fanfest?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;font-weight: inherit">Cheer on UCSB Soccer</a></strong></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer e2ma-button" id="block_hiahvaft" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="e2ma-holder" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;padding: 0 40px 60px 40px;background-color: #fff" width="100%"> <tbody><tr> <td align="left"> <table class="c-collapsed-table" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;border-spacing: 0"> <tbody><tr> <td bgcolor="#047c91" style="-webkit-border-radius: 0px; -moz-border-radius: 0px; border-radius: 0px; box-sizing: border-box; "> <a href="https://www.alumni.ucsb.edu/events/upcoming-events?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline; padding: 12px 18px; font-size: 16px; font-family: 'Century Gothic', 'Apple Gothic', 'URW Gothic L', Futura, Arial, sans-serif; color: #ffffff; text-align: center; text-decoration: none; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; background-color: #047c91; font-style: normal; font-weight: bold; display: block; border: 1px solid #047c91; mso-line-height-rule: exactly; line-height:110%">View all events</a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_abpdtesk" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0;background-color: transparent" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 0px 0px 0px 0px; " valign="top"> <a href="https://www.alumni.ucsb.edu/vacation/alumni-tours?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga#ahi" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Alumni Tours: Galapagos. Start Exploring!" border="0" height="320" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/c7/cb/5f/03/07ff440cb734d0b74052857f_1280x640.png" style="display: block" width="640"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_nrldhhkq" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 50px 40px 10px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <h4 style="display: block;font-size: 15px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 16px;font-weight: normal;color: #003660"><strong>Trending Gaucho News: </strong><br/></h4> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_nmoejssl" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h3 style="display: block;font-size: 18px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;line-height: 21.6px"><span class="e2ma-style" style="color: rgb(4, 124, 145)">New hope for plastic recycling</span></h3>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_hpuxrfqc" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 10px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5">In this episode of Research in 60 Seconds, chemical engineer Susannah Scott introduces her groundbreaking "upcycling" method for producing high-quality plastic, advancing efforts toward a circular economy.<br/></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><strong><a data-name="tune into something new" data-type="url" href="https://www.ucsb.edu/research/research-in-60-seconds?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;font-weight: inherit">Dig into the research</a></strong></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_dxjcqqhm" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h3 style="display: block;font-size: 18px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;line-height: 21.6px"><span class="e2ma-style" style="color: rgb(4, 124, 145)">Powering up a semiconductor workforce</span></h3>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_unltfghv" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 10px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5">UC Santa Barbara partners with SB City College to expand workforce training in micro/nanotechnology and semiconductor manufacturing.<br/></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><strong><a data-name="check out the results" data-type="url" href="https://news.ucsb.edu/in-focus/uc-santa-barbara-partners-sb-city-college-expand-workforce-training-micronanotechnology?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;font-weight: inherit">Learn more</a></strong></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_cudrortf" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 40px 0 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block">
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
<h3 style="display: block;font-size: 18px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;line-height: 21.6px"><span class="e2ma-style" style="color: rgb(4, 124, 145)">Exploiting atomically thin materials for energy-efficient electronics</span></h3>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333"><span style="line-height: 1.5"></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_ylpivrtp" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 50px 40px;background-color: #fff" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5">Recent graduate student Arnab Pal receives a prestigious fellowship from the Electron Devices Society.<br/></span></div>
<div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><strong><a data-name="meet the tiny tenants" data-type="url" href="https://news.ucsb.edu/in-focus/exploiting-atomically-thin-materials-energy-efficient-electronics?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;font-weight: inherit">Plug into the research</a></strong></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_lqfzrdlf" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 30px 40px 10px 40px;background-color: #003660" valign="top"> <div class="e2ma-content-block"> <h3 style="display: block;font-size: 18px;font-weight: bold;color: #000;margin: 0 0 12px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 18px;line-height: 22px;font-weight: 600;color: #04859B"><span style="color: rgb(0, 54, 96); font-size: 18px"><span class="e2ma-style" style='font-family: "Century Gothic", sans-serif'><span class="e2ma-style" style="color: rgb(254, 188, 17); font-size: 18px"><strong>Trivia Answer:</strong></span></span></span></h3> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_qwoefiqt" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 0 40px 30px 40px;background-color: #003660" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(255, 255, 255)"><strong></strong></span><span class="e2ma-style" style="color: rgb(255, 255, 255)"><strong><span class="e2ma-style" style="font-size: 18px">While its roots date back to 1921 with football (yes, we once had a football team), the Blue-Green Rivalry between the Gauchos and Cal Poly's Mustangs was officially established on the soccer pitch in 2012.</span><br/></strong></span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_txlxusvk" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 0 10px 0;background-color: transparent" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;text-indent: 140px"><span style="line-height: 1.5"><span class="e2ma-style" style="font-size: 13px; color: rgb(122, 122, 122)">                     A message from an Alumni Partner:</span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_itqttlib" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 40px 20px 40px;background-color: transparent" valign="top"> <table align="left" border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="1%"> <tbody><tr> <td style=" padding: 0px 25px 0px 0px; " valign="top" width="1%"> <div align="center" style="mso-table-lspace:0;mso-table-rspace:9"> <a href="https://www.gogoleta.com/?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="GoGoleta" border="0" height="74" src="https://d31hzlhk6di2h5.cloudfront.net/20240926/1f/8d/ac/7b/47f5349f2548289639607cb9_512x148.jpeg" style="display: block" width="256"/> </a> </div>
</td> </tr> </tbody></table> <div class="e2ma-combo-content e2ma-content-block" style="font-size: 12px;line-height: 1.5"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;text-align: center; line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(17, 124, 192)"><strong><span class="e2ma-style" style="font-size: 16px">From outdoor thrills</span><br/><span class="e2ma-style" style="font-size: 16px"> to tranquil escapes, <br/><a data-name="Goleta the Goodland" data-type="url" href="https://www.gogoleta.com/?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;font-weight: inherit; color: rgb(17, 124, 192)">Goleta the Goodland has it all</a>!</span></strong></span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_llapqyle" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 40px 40px 10px 40px;background-color: #047c91" valign="top"> <div class="e2ma-content-block"> <h2 style="display: block;font-size: 24px;font-weight: bold;color: #444;margin: 0 0 18px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 24px;line-height: 28px;font-weight: 600;color: #FEBC11;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 24px;line-height: 28px;font-weight: 600;color: #FEBC11"><strong><span style="text-decoration: none">Stay in the loop</span></strong></h2> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_kboczgvt" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 10px 40px;background-color: #047c91" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(255, 255, 255)"><a data-name="The Current" data-type="url" href="https://www.news.ucsb.edu/subscribe?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;color: rgb(255, 255, 255)"><strong>Subscribe to The Current</strong></a>, the official source of news for our campus community.</span></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_emweyttl" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 10px 40px 10px 40px;background-color: #047c91" valign="top"> <div class="e2ma-content-block"> <div class="e2ma-p-div" style="display: block;margin-bottom: 10px;font-size: 12px;font-weight: normal;line-height: 1.5;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;font-family: 'Century Gothic', sans-serif;font-size: 16px;line-height: 20px;color: #333;line-height: 22.4px"><span style="line-height: 1.5"><span class="e2ma-style" style="color: rgb(255, 255, 255)"><a data-name="Subscribe to the Magazine" data-type="url" href="https://magazine.ucsb.edu/subscribe?utm_source=alumni&amp;utm_medium=email&amp;utm_campaign=%40ucsb&amp;utm_content=sep-2024-ga" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline;color: rgb(255, 255, 255)"><strong>Subscribe to UC Santa Barbara Magazine</strong></a>, the digital version of our biannual magazine.</span><br/></span></div>
</div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_hcaqucir" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper e2ma-image-td" style="padding-right: 0;padding-bottom: 0;padding-left: 0;font-size: 12px;line-height: 1.5" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder" style="padding: 20px 40px 0 40px;background-color: #047c91" valign="top"> <div class="e2ma-content-block"> <h2 style="display: block;font-size: 24px;font-weight: bold;color: #444;margin: 0 0 18px 0;line-height: 1.3;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 24px;line-height: 28px;font-weight: 600;color: #FEBC11;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;font-family: 'Century Gothic', sans-serif;font-size: 24px;line-height: 28px;font-weight: 600;color: #FEBC11">Follow us</h2> </div>
</td> </tr> </tbody></table> </td> </tr> </tbody></table>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-block-outer" id="block_dggfvsrl" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-wrapper" style="padding-right: 0;padding-bottom: 0;padding-left: 0" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"> <tbody><tr> <td class="e2ma-holder e2ma-follow-holder" style="padding: 10px 30px 40px 30px;background-color: #047c91" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"> <tbody><tr><td valign="top"><table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px"><tbody><tr> <td class="e2ma-image-td" style="text-align: center; padding: 10px 10px 10px 10px; " valign="top"> <a href="http://www.facebook.com/UCSBAlumni/" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Facebook" border="0" height="48" src="http://d1v4jtnvxv2013.cloudfront.net/media/images/mailing-create/editor/social-follow/color-circle-facebook.png" style="display: block" width="48"/> </a> </td> <td class="e2ma-image-td" style="text-align: center; padding: 10px 10px 10px 0px; " valign="top"> <a href="http://www.instagram.com/ucsbalumni/" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="Instagram" border="0" height="48" src="http://d1v4jtnvxv2013.cloudfront.net/media/images/mailing-create/editor/social-follow/color-circle-instagram.png" style="display: block" width="48"/> </a> </td> <td class="e2ma-image-td" style="text-align: center; padding: 10px 10px 10px 0px; " valign="top"> <a href="http://www.linkedin.com/groups/55812/profile" style="font-weight: normal;font-weight: normal;color: #005099;text-decoration: underline;color: #005099;text-decoration: underline" target="_blank"> <img alt="LinkedIn" border="0" height="48" src="http://d1v4jtnvxv2013.cloudfront.net/media/images/mailing-create/editor/social-follow/color-circle-linkedin.png" style="display: block" width="48"/> </a> </td> </tr></tbody></table></td></tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
</td></tr></tbody></table></div>
<table border="0" cellpadding="0" cellspacing="0" class="e2ma-row-region-content e2ma-section" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%"><tbody><tr><td class="e2ma-layout-column-content"></td></tr></tbody></table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td align="center" class="e2ma-design-option-footer" data-e2ma-styles="background" style="background-repeat: repeat;background-color: transparent;background-attachment: scroll;background-position: center center">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%">
<tbody><tr>
<td align="center" style="padding:10px">
<div class="e2ma-tag-outer">
<div class="e2ma-p-div" style="font-size: inherit"><br/>
</div>
</div>
</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td align="center" bgcolor="#F6F7F8" class="e2ma-unsubscribe" style="padding-bottom: 10px;padding-bottom: 10px;padding:50px 0px" valign="top">
<table border="0" cellpadding="0" cellspacing="0" class="mobile-width" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px;width: 640px">
<tbody><tr>
<td align="left" valign="top">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%">
<tbody><tr>
<td align="left" class="stack" valign="top">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%">
<tbody><tr>
<td align="left" class="share-block center" valign="top">
<table align="left" border="0" cellpadding="0" cellspacing="0" class="mobile-width" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="166"> <tbody><tr> <td align="center" valign="top"> <table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="166"> <tbody><tr> <td align="left" class="center" style="font-family:Helvetica, Arial, sans-serif; color:#9d9e9f; font-size:12px; line-height:1.5; letter-spacing:1px; text-align:left; padding-bottom:5px" valign="top"> <strong>Share this email:</strong> </td> </tr> <tr> <td align="left" valign="top"> <table border="0" cellpadding="0" cellspacing="0" class="center" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="auto"> <tbody><tr> <td align="left" class="footer-social" style="width:34px;padding-right:10px" valign="top"> <a href="http://t.e2ma.net/sendtofriend/:account_id/awb8vj/" style="font-weight: normal;font-weight: normal"><img alt="Email" border="0" class="footer-social" height="33" src="https://d1v4jtnvxv2013.cloudfront.net/media/images/themes/editor/img/socialnetworks/social-email.png" style="display:block; font-size:7px; font-family:arial,serif" width="34"/></a> </td> <td align="left" class="footer-social" style="width:34px;padding-right:10px" valign="top"> <a href="https://twitter.com/intent/tweet?text=A%20plastic%20upcycling%20innovation+https://t.e2ma.net/webview/awb8vj/106aa11ee581b5d415467545a32e231a" style="font-weight: normal;font-weight: normal"><img alt="Twitter" border="0" class="footer-social" height="33" src="https://d1v4jtnvxv2013.cloudfront.net/media/images/themes/editor/img/socialnetworks/social-twitter.png" style="display:block; font-size:7px; font-family:arial,serif" width="34"/></a> </td> <td align="left" class="footer-social" style="width:34px;padding-right:10px" valign="top"> <a href="http://www.facebook.com/share.php?u=https://t.e2ma.net/webview/awb8vj/106aa11ee581b5d415467545a32e231a" style="font-weight: normal;font-weight: normal"><img alt="Facebook" border="0" class="footer-social" height="33" src="https://d1v4jtnvxv2013.cloudfront.net/media/images/themes/editor/img/socialnetworks/social-facebook.png" style="display:block; font-size:7px; font-family:arial,serif" width="34"/></a> </td> <td align="left" class="footer-social" style="width:34px" valign="top"> <a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=https://t.e2ma.net/webview/awb8vj/106aa11ee581b5d415467545a32e231a" style="font-weight: normal;font-weight: normal"><img alt="LinkedIn" border="0" class="footer-social" height="33" src="https://d1v4jtnvxv2013.cloudfront.net/media/images/themes/editor/img/socialnetworks/social-linkedin.png" style="display:block; font-size:7px; font-family:arial,serif" width="34"/></a> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table>
</td>
</tr>
<tr>
<td align="left" class="center" style="font-family:'Century Gothic', sans-serif; color:#333333; font-size:13px; line-height:1.8; text-align:left; padding:20px 0px" valign="top">Choose the emails you would like to receive by <a href="#" style="font-weight: normal;font-weight: normal;font-weight: 600;font-size: 13px;color: #003660"> managing your preferences.</a> <br/>
<br/><div class="e2ma-p-div" style="font-size: 12px;color: #898989">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             If you do not wish to receive any emails from UC Santa Barbara Institutional Advancement (this includes event invitations, newsletters, networking opportunities and stories of philanthropy), you can                                                                                                                                                                                                                                                                                                                        <a href="#" style="font-weight: normal;font-weight: normal;color:#003660; text-decoration:underline"><strong>opt out of them ALL</strong></a> using TrueRemove®<br/>
</div>
</td>
</tr>
<tr>
<td align="left" class="footer-text" style="font-family:Helvetica, Arial, sans-serif; font-size:11px; line-height:1.5; text-align:left" valign="top">
<a href="#" style="font-weight: normal;font-weight: normal;color:#9d9e9f; text-decoration:none; pointer-events:none">UC Santa Barbara <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Santa Barbara, CA | 93106 US</a>
</td>
</tr>
<tr>
<td align="left" class="footer-text" style="font-family:Helvetica, Arial, sans-serif;font-size:11px; line-height:1.5; text-align:left; padding-top:20px" valign="top">
<a href="" style="font-weight: normal;font-weight: normal;color:#9d9e9f; text-decoration:none">
This email was sent to . <br/>
<em>To continue receiving our emails, add us to your address book.</em>
</a>
</td>
</tr>
</tbody></table>
</td>
<td align="center" class="stack" style="width: 146px" valign="bottom">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="font-family: Arial, Helvetica, sans-serif;font-size: 12px" width="100%">
<tbody><tr>
<td align="center" style="padding-top:20px" valign="bottom">
<div></div>
</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>
</td>
</tr>
<tr>
<td align="left" style="line-height:0px; font-size:0px" valign="top">
<div style="line-height:0px; font-size:0px">#</div>
</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>
</div>
<div id="e2ma-join"><a href="https://app.e2ma.net/app2/audience/signup/1869388/1811880/?v=a">Subscribe</a> to our email list.</div></body>
"""

UCSBNewsletter = PromptArgs(naming_conventions, html_example_one, link_names_example_one, generated_link_names_example_one)
 